apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-blob-nfs
  annotations:
        volume.beta.kubernetes.io/storage-class: azureblob-nfs
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azureblob-nfs
  resources:
    requests:
      storage: 5Gi
---
kind: Pod
apiVersion: v1
metadata:
  name: nfspod
spec:
  containers:
  - name: nfspod
    image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
    volumeMounts:
    - mountPath: "/mnt/blob"
      name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: azure-blob-nfs
